name: test-workflow
on: [workflow_dispatch]

jobs:
  deploy-vm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.7.0
    - run: |
        cd ${{ github.workspace }}
        touch hello.txt
        pwd
        ls
